import type { Product, Category } from "./api";

export const FALLBACK_CATEGORIES: Category[] = [
  { slug: "chal", name: "চাল", icon: "🍚" },
  { slug: "dal", name: "ডাল", icon: "🫘" },
  { slug: "tel", name: "তেল", icon: "🛢️" },
  { slug: "sobji", name: "সবজি", icon: "🥬" },
  { slug: "mach", name: "মাছ", icon: "🐟" },
  { slug: "mangsho", name: "মাংস", icon: "🍗" },
  { slug: "dim-dui", name: "ডিম-দুধ", icon: "🥛" },
  { slug: "mosla", name: "মসলা", icon: "🌶️" },
];

export const FALLBACK_PRODUCTS: Product[] = [
  { id: 1, slug: "sorno-machi-chal", name: "স্বর্ণমাছি চাল", category: "chal", categoryNameBn: "চাল", emoji: "🍚", unit: "kg", todayPrice: 148, changePercent: 2.1, markets: [] },
  { id: 2, slug: "miniket-chal", name: "মিনিকেট চাল", category: "chal", categoryNameBn: "চাল", emoji: "🍚", unit: "kg", todayPrice: 99, changePercent: -2.9, markets: [] },
  { id: 3, slug: "nazir-chal", name: "নাজির চাল", category: "chal", categoryNameBn: "চাল", emoji: "🍚", unit: "kg", todayPrice: 74, changePercent: 0, markets: [] },
  { id: 4, slug: "batam-size-chal", name: "বাটাম সাইজ চাল", category: "chal", categoryNameBn: "চাল", emoji: "🍚", unit: "kg", todayPrice: 66, changePercent: 3.1, markets: [] },
  { id: 5, slug: "mosur-dal", name: "মসুর ডাল", category: "dal", categoryNameBn: "ডাল", emoji: "🫘", unit: "kg", todayPrice: 142, changePercent: 2.9, markets: [] },
  { id: 6, slug: "mug-dal", name: "মুগ ডাল", category: "dal", categoryNameBn: "ডাল", emoji: "🫘", unit: "kg", todayPrice: 135, changePercent: 0, markets: [] },
  { id: 7, slug: "chola-dal", name: "ছোলা", category: "dal", categoryNameBn: "ডাল", emoji: "🫘", unit: "kg", todayPrice: 120, changePercent: -2.4, markets: [] },
  { id: 8, slug: "aman-dal-khosasila", name: "আমন ডাল (খোসাসিলা)", category: "dal", categoryNameBn: "ডাল", emoji: "🫘", unit: "kg", todayPrice: 156, changePercent: 2.6, markets: [] },
  { id: 9, slug: "sorishar-tel", name: "সরিষার তেল", category: "tel", categoryNameBn: "তেল", emoji: "🫙", unit: "litre", todayPrice: 192, changePercent: 2.1, markets: [] },
  { id: 10, slug: "pam-tel", name: "পাম তেল", category: "tel", categoryNameBn: "তেল", emoji: "🛢️", unit: "kg", todayPrice: 168, changePercent: -2.3, markets: [] },
  { id: 11, slug: "ghani-banga-sorishar-tel", name: "ঘানি ভাঙা সরিষার তেল", category: "tel", categoryNameBn: "তেল", emoji: "🫙", unit: "litre", todayPrice: 215, changePercent: 2.4, markets: [] },
  { id: 12, slug: "alu", name: "আলু", category: "sobji", categoryNameBn: "সবজি", emoji: "🥔", unit: "kg", todayPrice: 30, changePercent: -6.2, markets: [] },
  { id: 13, slug: "peyaj", name: "পেঁয়াজ", category: "sobji", categoryNameBn: "সবজি", emoji: "🧅", unit: "kg", todayPrice: 54, changePercent: 12.5, markets: [] },
  { id: 14, slug: "kaccha-moric", name: "কাঁচামরিচ", category: "sobji", categoryNameBn: "সবজি", emoji: "🌶️", unit: "kg", todayPrice: 92, changePercent: -12.4, markets: [] },
  { id: 15, slug: "begun", name: "বেগুন", category: "sobji", categoryNameBn: "সবজি", emoji: "🍆", unit: "kg", todayPrice: 44, changePercent: 4.8, markets: [] },
  { id: 16, slug: "dhenders", name: "ঢেঁড়স", category: "sobji", categoryNameBn: "সবজি", emoji: "🟢", unit: "kg", todayPrice: 38, changePercent: 0, markets: [] },
  { id: 17, slug: "rui-mach", name: "রুই মাছ", category: "mach", categoryNameBn: "মাছ", emoji: "🐟", unit: "kg", todayPrice: 46, changePercent: 4.5, markets: [] },
  { id: 18, slug: "telapiya-mach", name: "তেলাপিয়া", category: "mach", categoryNameBn: "মাছ", emoji: "🐟", unit: "kg", todayPrice: 36, changePercent: 0, markets: [] },
  { id: 19, slug: "ilish-mach", name: "ইলিশ মাছ", category: "mach", categoryNameBn: "মাছ", emoji: "🐠", unit: "kg", todayPrice: 1850, changePercent: 3.4, markets: [] },
  { id: 20, slug: "katla-mach", name: "কাতলা মাছ", category: "mach", categoryNameBn: "মাছ", emoji: "🐠", unit: "kg", todayPrice: 43, changePercent: -4.4, markets: [] },
  { id: 21, slug: "chingri-mach", name: "চিংড়ি মাছ (খোলা)", category: "mach", categoryNameBn: "মাছ", emoji: "🦐", unit: "kg", todayPrice: 330, changePercent: 3.1, markets: [] },
  { id: 22, slug: "murgi-r-mangsho", name: "মুরগির মাংস", category: "mangsho", categoryNameBn: "মাংস", emoji: "🍗", unit: "kg", todayPrice: 225, changePercent: -1.3, markets: [] },
  { id: 23, slug: "goru-r-mangsho", name: "গরুর মাংস", category: "mangsho", categoryNameBn: "মাংস", emoji: "🥩", unit: "kg", todayPrice: 790, changePercent: -1.2, markets: [] },
  { id: 24, slug: "khasir-mangsho", name: "খাসির মাংস", category: "mangsho", categoryNameBn: "মাংস", emoji: "🍖", unit: "kg", todayPrice: 1290, changePercent: -3, markets: [] },
  { id: 25, slug: "hanser-mangsho", name: "হাঁসের মাংস", category: "mangsho", categoryNameBn: "মাংস", emoji: "🦆", unit: "kg", todayPrice: 285, changePercent: -3.4, markets: [] },
  { id: 26, slug: "dim", name: "ডিম", category: "dim-dui", categoryNameBn: "ডিম-দুধ", emoji: "🥚", unit: "dozen", todayPrice: 158, changePercent: 3.9, markets: [] },
  { id: 27, slug: "dui-dudh", name: "দুধ", category: "dim-dui", categoryNameBn: "ডিম-দুধ", emoji: "🥛", unit: "litre", todayPrice: 102, changePercent: 2, markets: [] },
  { id: 28, slug: "doi", name: "দই", category: "dim-dui", categoryNameBn: "ডিম-দুধ", emoji: "🥣", unit: "litre", todayPrice: 92, changePercent: 0, markets: [] },
  { id: 29, slug: "mokhhan", name: "মাখন (১০০ গ্রাম)", category: "dim-dui", categoryNameBn: "ডিম-দুধ", emoji: "🧈", unit: "piece", todayPrice: 145, changePercent: 3.6, markets: [] },
  { id: 30, slug: "ada", name: "আদা", category: "mosla", categoryNameBn: "মসলা", emoji: "🫚", unit: "kg", todayPrice: 85, changePercent: 9, markets: [] },
  { id: 31, slug: "roshun", name: "রসুন", category: "mosla", categoryNameBn: "মসলা", emoji: "🧄", unit: "kg", todayPrice: 125, changePercent: -7.4, markets: [] },
  { id: 32, slug: "morich-gunda", name: "মরিচ গুঁড়া", category: "mosla", categoryNameBn: "মসলা", emoji: "🌶️", unit: "kg", todayPrice: 245, changePercent: -2, markets: [] },
  { id: 33, slug: "dhanepata-gunda", name: "ধনেপাতা গুঁড়া", category: "mosla", categoryNameBn: "মসলা", emoji: "🍃", unit: "kg", todayPrice: 265, changePercent: 0, markets: [] },
];